import React from "react";
import Badge from "../../components/common/Badge";
import { concepts } from "../../data/demoData";
import { BarChartCard, LineChartCard } from "../../components/common/ChartCard";
export default function AnalyticsPage({state,students=[]}){
 const rows=[]; const bars=[]; const trend=[];
 return <div><div className="page-kicker">Learning Analytics</div><h1 className="page-title">Analitik Pembelajaran</h1><p className="page-desc">Dashboard guru untuk membaca mastery, perkembangan belajar, miskonsepsi, dan efektivitas soal.</p>
 <div className="stats-row"><div className="ac-stat"><div className="stat-icon purple">◈</div><div><span>Rata-rata Penguasaan</span><strong>—</strong></div></div><div className="ac-stat"><div className="stat-icon green">✓</div><div><span>Konsep Dikuasai</span><strong>—</strong></div></div><div className="ac-stat"><div className="stat-icon orange">!</div><div><span>Miskonsepsi Aktif</span><strong>—</strong></div></div><div className="ac-stat"><div className="stat-icon blue">♙</div><div><span>Jumlah Siswa</span><strong>{students.length}</strong></div></div></div>
 <div className="analytics-grid"><div className="card"><div className="empty-state"><strong>Belum ada data analitik siswa.</strong><span>Grafik mastery, miskonsepsi, dan tren akan dihitung setelah siswa terdaftar dan mulai melakukan aktivitas belajar.</span></div></div><div className="card"><div className="empty-state"><strong>Belum ada tren pembelajaran.</strong><span>Data akan muncul otomatis dari attempt dan learning event siswa.</span></div></div></div>
 <div className="dashboard-grid"><div className="card"><div className="section-head"><div><h2>Distribusi Kemampuan Siswa</h2><span>Kelompok berdasarkan tingkat penguasaan</span></div><Badge tone="blue">{students.length} siswa</Badge></div><div className="ability-bars"><div><span>Perlu penguatan</span><b>—</b></div><div><span>Dalam proses</span><b>—</b></div><div><span>Menguasai</span><b>—</b></div></div></div><div className="card"><div className="section-head"><div><h2>Rekomendasi Guru</h2><span>Dari student model</span></div></div><div className="recommend-card" style={{boxShadow:"none",border:0,padding:0}}><span>Konsep prioritas</span><strong>Belum ada konsep prioritas.</strong><div className="progress-label"><span>Mastery</span><b>—</b></div><div className="progress"><span style={{width:"0%"}}/></div></div></div></div>
 <div className="card" style={{marginTop:16}}><div className="empty-state"><strong>Mastery detail belum tersedia.</strong><span>Detail per konsep akan diambil dari Student Model siswa pada kelas yang dipilih.</span></div></div></div>
}
