import React,{useMemo,useState} from "react";
import Badge from "../../components/common/Badge";
import { BarChartCard, LineChartCard } from "../../components/common/ChartCard";
import { Download, Sparkles } from "lucide-react";
import { analyzeClassWithAI } from "../../services/tutorService";
import { downloadAnalyticsExcel } from "../../utils/exportAnalyticsExcel";

export default function AnalyticsPage({students=[],models=[],attempts=[],events=[],examResults=[],teacherClasses=[],onRefresh}){
 const [school,setSchool]=useState(""); const [grade,setGrade]=useState(""); const [rombel,setRombel]=useState(""); const [aiResult,setAiResult]=useState(null); const [aiLoading,setAiLoading]=useState(false);
 const safeStudents=Array.isArray(students)?students:[]; const safeModels=Array.isArray(models)?models:[]; const safeAttempts=Array.isArray(attempts)?attempts:[]; const safeEvents=Array.isArray(events)?events:[]; const safeExam=Array.isArray(examResults)?examResults:[]; const classes=Array.isArray(teacherClasses)?teacherClasses:[];
 const byUid=useMemo(()=>new Map(safeModels.map(m=>[m.uid,m])),[safeModels]);
 const schools=[...new Set(classes.map(c=>c.school).filter(Boolean))]; const grades=[...new Set(classes.filter(c=>!school||c.school===school).map(c=>c.grade).filter(Boolean))]; const rombels=[...new Set(classes.filter(c=>(!school||c.school===school)&&(!grade||c.grade===grade)).map(c=>c.rombel).filter(Boolean))];
 const classRows=classes.filter(c=>(!school||c.school===school)&&(!grade||c.grade===grade)&&(!rombel||String(c.rombel)===String(rombel))); const selectedIds=new Set(classRows.map(c=>c.id));
 const rows=useMemo(()=>safeStudents.filter(s=>selectedIds.has(s.classId)||(!s.classId&&(!school||s.school===school)&&(!grade||s.grade===grade)&&(!rombel||String(s.rombel)===String(rombel)))).map(s=>({...s,model:byUid.get(s.uid)||s.model||{}})),[safeStudents,selectedIds,school,grade,rombel,byUid]);
 const studentIds=new Set(rows.map(r=>r.uid)); const scopedAttempts=safeAttempts.filter(a=>studentIds.has(a.uid)); const scopedEvents=safeEvents.filter(e=>studentIds.has(e.uid)); const scopedExam=safeExam.filter(e=>studentIds.has(e.uid));
 const practiceByStudent=new Map(); scopedAttempts.filter(a=>(a.mode||"practice")==="practice").forEach(a=>{const x=practiceByStudent.get(a.uid)||{n:0,c:0};x.n++;if(a.correct)x.c++;practiceByStudent.set(a.uid,x);});
 const eventByStudent=new Map(); scopedEvents.forEach(e=>{const x=eventByStudent.get(e.uid)||{seconds:0,tutor:0,panel:0};if(e.type==="app_session"||e.type==="screen_time")x.seconds+=Number(e.durationSeconds||0);if(e.type==="tutor_message")x.tutor++;if(e.type==="comic_panel_view")x.panel++;eventByStudent.set(e.uid,x);});
 const conceptMap={}; rows.forEach(r=>Object.entries(r.model?.concepts||{}).forEach(([id,p])=>{const x=conceptMap[id]||{values:[],attempts:0,mis:0};x.values.push(Number(p?.mastery||0));x.attempts+=Number(p?.attempts||0);x.mis+=(r.model?.misconceptions||[]).filter(m=>m.conceptId===id&&!m.resolved).length;conceptMap[id]=x;}));
 const conceptRows=Object.entries(conceptMap).map(([id,x])=>{const value=x.values.length?Math.round(x.values.reduce((a,b)=>a+b,0)/x.values.length*100):0;return {id,value,attempts:x.attempts,activeMisconceptions:x.mis,status:value>=80?"Menguasai":value>=50?"Dalam proses":"Perlu penguatan"};}).sort((a,b)=>a.value-b.value);
 const topMastery=conceptRows.slice().sort((a,b)=>b.value-a.value).slice(0,5); const priorityConcepts=conceptRows.slice(0,5);
 const misconceptionMap={}; rows.forEach(r=>(r.model?.misconceptions||[]).filter(m=>!m.resolved).forEach(m=>{const key=`${m.conceptId||"-"} · ${m.tag||"MISKONSEPSI"}`;misconceptionMap[key]=(misconceptionMap[key]||0)+1;}));
 const misconceptionRows=Object.entries(misconceptionMap).map(([label,count])=>({label,count})).sort((a,b)=>b.count-a.count); const totalMis=misconceptionRows.reduce((n,x)=>n+x.count,0);
 const masteryValues=rows.map(r=>Number(r.model?.overallMastery||0)); const avgMastery=masteryValues.length?Math.round(masteryValues.reduce((a,b)=>a+b,0)/masteryValues.length*100):0;
 const buckets=[{label:"Dasar (<50%)",value:rows.filter(r=>(r.model?.overallMastery||0)<.5).length},{label:"Berkembang (50–79%)",value:rows.filter(r=>(r.model?.overallMastery||0)>=.5&&(r.model?.overallMastery||0)<.8).length},{label:"Menguasai (≥80%)",value:rows.filter(r=>(r.model?.overallMastery||0)>=.8).length}];
 const trend=scopedAttempts.slice(0,10).reverse().map((a,i)=>({label:`${i+1}`,value:Number(a.score??(a.correct?100:0))}));
 const studentRows=rows.map(r=>{const p=practiceByStudent.get(r.uid)||{n:0,c:0};const ev=eventByStudent.get(r.uid)||{seconds:0,tutor:0,panel:0};const exam=scopedExam.filter(x=>x.uid===r.uid).sort((a,b)=>String(b.createdAt||"").localeCompare(String(a.createdAt||"")))[0];const mis=(r.model?.misconceptions||[]).filter(m=>!m.resolved).length;return {...r,mastery:Math.round(Number(r.model?.overallMastery||0)*100),practiceAttempts:p.n,practiceScore:p.n?Math.round(p.c/p.n*100):0,examScore:exam?.score??r.exam??0,learningMinutes:Math.round(ev.seconds/60),tutorInteractions:ev.tutor,panelViews:ev.panel,activeMisconceptions:mis};}).sort((a,b)=>b.mastery-a.mastery);
 async function runAI(){setAiLoading(true);try{setAiResult(await analyzeClassWithAI({classData:{school,grade,rombel,studentCount:rows.length,avgMastery,topMastery,priorityConcepts,misconceptions:misconceptionRows,studentNeeds:studentRows.slice().sort((a,b)=>a.mastery-b.mastery).slice(0,8).map(s=>`${s.name}: mastery ${s.mastery}%, latihan ${s.practiceScore}%`)}}));}finally{setAiLoading(false)}}
 function exportData(){downloadAnalyticsExcel({studentRows,conceptRows,className:[school,grade,rombel].filter(Boolean).join("-")||"Kelas"});}
 return <div><div className="page-kicker">Learning Analytics</div><h1 className="page-title">Analitik Pembelajaran</h1><p className="page-desc">Analitik merepresentasikan mastery, latihan, miskonsepsi, kebutuhan siswa, dan penggunaan web berdasarkan aktivitas nyata.</p>
  <div className="card" style={{marginBottom:18}}><div className="section-head"><div><h2>Kontrol Kelas</h2><span>Data mengikuti kelas yang dikelola Guru.</span></div><div className="actions"><button className="btn" onClick={onRefresh}>↻ Perbarui</button><button className="btn-primary" onClick={exportData} disabled={!rows.length}><Download size={15}/> Unduh Excel</button></div></div><div className="register-grid"><div><label className="label">Sekolah</label><select value={school} onChange={e=>{setSchool(e.target.value);setGrade("");setRombel("")}}><option value="">Semua sekolah</option>{schools.map(v=><option key={v}>{v}</option>)}</select></div><div><label className="label">Kelas</label><select value={grade} onChange={e=>{setGrade(e.target.value);setRombel("")}}><option value="">Semua kelas</option>{grades.map(v=><option key={v}>{v}</option>)}</select></div><div><label className="label">Rombel</label><select value={rombel} onChange={e=>setRombel(e.target.value)}><option value="">Semua rombel</option>{rombels.map(v=><option key={v}>{v}</option>)}</select></div></div></div>
  <div className="stats-row"><div className="ac-stat"><div className="stat-icon purple">◈</div><div><span>Rata-rata Penguasaan</span><strong>{avgMastery}%</strong></div></div><div className="ac-stat"><div className="stat-icon green">✓</div><div><span>Konsep Dikuasai</span><strong>{conceptRows.filter(x=>x.value>=80).length}</strong></div></div><div className="ac-stat"><div className="stat-icon orange">!</div><div><span>Miskonsepsi Aktif</span><strong>{totalMis}</strong></div></div><div className="ac-stat"><div className="stat-icon blue">♙</div><div><span>Jumlah Siswa</span><strong>{rows.length}</strong></div></div></div>
  <div className="stats-row" style={{marginTop:12}}><div className="ac-stat"><div className="stat-icon purple">◷</div><div><span>Waktu Belajar</span><strong>{Math.round(studentRows.reduce((n,r)=>n+r.learningMinutes,0))} mnt</strong></div></div><div className="ac-stat"><div className="stat-icon blue">💬</div><div><span>Interaksi Tutor</span><strong>{studentRows.reduce((n,r)=>n+r.tutorInteractions,0)}</strong></div></div><div className="ac-stat"><div className="stat-icon green">▣</div><div><span>Panel Dibaca</span><strong>{studentRows.reduce((n,r)=>n+r.panelViews,0)}</strong></div></div><div className="ac-stat"><div className="stat-icon orange">✓</div><div><span>Attempt Latihan</span><strong>{studentRows.reduce((n,r)=>n+r.practiceAttempts,0)}</strong></div></div></div>
  {rows.length?<><div className="analytics-grid"><BarChartCard title="Distribusi Kemampuan" subtitle="Distribusi siswa berdasarkan mastery aktual" data={buckets}/>{trend.length?<LineChartCard title="Tren Attempt" subtitle="Urutan skor attempt terbaru" data={trend}/>:<div className="card empty-state"><strong>Belum ada tren.</strong><span>Data muncul setelah siswa mengerjakan latihan.</span></div>}</div>
   <div className="analytics-grid" style={{marginTop:16}}><div className="card"><div className="section-head"><div><h2>Top Mastery</h2><span>Konsep dengan penguasaan tertinggi</span></div><Badge tone="green">Unggul</Badge></div>{topMastery.map(x=><div className="list-item" key={x.id}><span><strong>{x.id}</strong><small className="subtle"> · {x.attempts} attempt</small></span><strong>{x.value}%</strong></div>)}</div><div className="card"><div className="section-head"><div><h2>Prioritas Penguatan</h2><span>Konsep dengan mastery terendah</span></div><Badge tone="amber">Prioritas</Badge></div>{priorityConcepts.map(x=><div className="list-item" key={x.id}><span><strong>{x.id}</strong><small className="subtle"> · {x.activeMisconceptions} miskonsepsi</small></span><strong>{x.value}%</strong></div>)}</div></div>
   <div className="analytics-grid" style={{marginTop:16}}><div className="card"><div className="section-head"><div><h2>Top Miskonsepsi</h2><span>Pola kesalahan yang paling sering terdeteksi AI</span></div></div>{misconceptionRows.length?misconceptionRows.slice(0,5).map(x=><div className="list-item" key={x.label}><span>{x.label}</span><Badge tone="amber">{x.count} siswa/kejadian</Badge></div>):<div className="empty-state"><strong>Belum ada miskonsepsi aktif.</strong><span>Diagnosis AI muncul setelah siswa mengerjakan latihan.</span></div>}</div><div className="card"><div className="section-head"><div><h2>AI Analisis Kelas</h2><span>AI membaca pola agregat untuk membantu guru mengambil tindakan.</span></div><Sparkles size={18}/></div><button className="btn-primary" onClick={runAI} disabled={aiLoading}>{aiLoading?"AI sedang menganalisis…":"✨ Analisis kelas dengan AI"}</button>{aiResult&&<div className="ai-feedback" style={{marginTop:12}}><strong>{aiResult.ai===false?"Analisis berbasis data":"Analisis AI"}</strong><p>{aiResult.summary}</p>{aiResult.recommendations?.map((x,i)=><div className="list-item" key={i}><span>{x}</span></div>)}</div>}</div></div>
   <div className="card" style={{marginTop:16}}><div className="section-head"><div><h2>Statistik Antar Siswa</h2><span>Mastery, latihan, ujian, penggunaan web, dan miskonsepsi per siswa.</span></div></div><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Siswa</th><th>Kelas</th><th>Mastery</th><th>Latihan</th><th>Ujian</th><th>Waktu</th><th>Tutor</th><th>Panel</th><th>Miskonsepsi</th></tr></thead><tbody>{studentRows.map(s=><tr key={s.uid}><td><strong>{s.name}</strong></td><td>{s.grade||"-"} {s.rombel||""}</td><td>{s.mastery}%</td><td>{s.practiceScore}% ({s.practiceAttempts})</td><td>{s.examScore}</td><td>{s.learningMinutes} mnt</td><td>{s.tutorInteractions}</td><td>{s.panelViews}</td><td>{s.activeMisconceptions}</td></tr>)}</tbody></table></div></div>
  </>:<div className="card empty-state"><strong>{classes.length?"Belum ada siswa pada filter ini.":"Belum ada kelas yang dikelola."}</strong><span>Data analitik akan muncul setelah siswa terhubung dan melakukan aktivitas.</span></div>}</div>;
}
