import React from "react";
import Badge from "../../components/common/Badge";
import { concepts } from "../../data/demoData";
import { BarChartCard, LineChartCard } from "../../components/common/ChartCard";
export default function AnalyticsPage({state}){
 const rows=Object.entries(state.studentModel.concepts);const weakest=[...rows].sort((a,b)=>a[1].mastery-b[1].mastery)[0];
 const bars=rows.map(([id,p])=>({label:id,value:Math.round(p.mastery*100)}));
 const trend=[{label:"Sen",value:61},{label:"Sel",value:65},{label:"Rab",value:64},{label:"Kam",value:70},{label:"Jum",value:68},{label:"Sab",value:74},{label:"Min",value:77}];
 return <div><div className="page-kicker">Learning Analytics</div><h1 className="page-title">Analitik Pembelajaran</h1><p className="page-desc">Dashboard guru untuk membaca mastery, perkembangan belajar, miskonsepsi, dan efektivitas soal.</p>
 <div className="stats-row"><div className="ac-stat"><div className="stat-icon purple">◈</div><div><span>Rata-rata Penguasaan</span><strong>72%</strong></div></div><div className="ac-stat"><div className="stat-icon green">✓</div><div><span>Konsep Dikuasai</span><strong>4 / 6</strong></div></div><div className="ac-stat"><div className="stat-icon orange">!</div><div><span>Miskonsepsi Aktif</span><strong>{state.studentModel.misconceptions.filter(m=>!m.resolved).length}</strong></div></div><div className="ac-stat"><div className="stat-icon blue">♙</div><div><span>Jumlah Siswa</span><strong>32</strong></div></div></div>
 <div className="analytics-grid"><BarChartCard title="Mastery per Konsep" subtitle="Persentase penguasaan konsep siswa" data={bars} max={100}/><LineChartCard title="Perkembangan Penguasaan" subtitle="Tren mastery selama aktivitas pembelajaran" data={trend}/></div>
 <div className="dashboard-grid"><div className="card"><div className="section-head"><div><h2>Distribusi Kemampuan Siswa</h2><span>Kelompok berdasarkan tingkat penguasaan</span></div><Badge tone="blue">32 siswa</Badge></div><div className="ability-bars"><div><span>Perlu penguatan</span><b>6</b></div><div><span>Dalam proses</span><b>12</b></div><div><span>Menguasai</span><b>14</b></div></div></div><div className="card"><div className="section-head"><div><h2>Rekomendasi Guru</h2><span>Dari student model</span></div></div><div className="recommend-card" style={{boxShadow:"none",border:0,padding:0}}><span>Konsep prioritas</span><strong>{weakest?.[0]} · {concepts[weakest?.[0]]?.name}</strong><div className="progress-label"><span>Mastery</span><b>{Math.round((weakest?.[1]?.mastery||0)*100)}%</b></div><div className="progress"><span style={{width:`${(weakest?.[1]?.mastery||0)*100}%`}}/></div></div></div></div>
 <div className="card" style={{marginTop:16}}><div className="section-head"><div><h2>Mastery Detail</h2><span>Student model terbaru</span></div></div><table className="table"><thead><tr><th>Konsep</th><th>Mastery</th><th>Confidence</th><th>Attempts</th><th>Status</th></tr></thead><tbody>{rows.map(([id,p])=><tr key={id}><td><strong>{id}</strong> · {concepts[id]?.name||id}</td><td>{Math.round(p.mastery*100)}%</td><td>{Math.round(p.confidence*100)}%</td><td>{p.attempts}</td><td><Badge tone={p.mastery>=.7?"green":p.mastery>=.5?"amber":"purple"}>{p.mastery>=.7?"Dikuasai":p.mastery>=.5?"Dalam Proses":"Perlu Penguatan"}</Badge></td></tr>)}</tbody></table></div></div>
}
