import React, { useMemo, useState } from "react";
import ComicCard from "../../components/comic/ComicCard";
import ConceptPicker from "../../components/common/ConceptPicker";

const EMPTY_FORM = { title:"", description:"", subject:"", educationLevel:"SMA", grade:"X", classId:"", className:"X 1", school:"", status:"Draft", concepts:[] };

export default function ComicManagement({ comics=[], teacherClasses=[], session, navigate, onCreate, onEdit }) {
  const [search,setSearch]=useState(""); const [statusFilter,setStatusFilter]=useState("Semua"); const [levelFilter,setLevelFilter]=useState("Semua"); const [schoolFilter,setSchoolFilter]=useState(""); const [classFilter,setClassFilter]=useState(""); const [open,setOpen]=useState(false); const [form,setForm]=useState(EMPTY_FORM);
  const schools=[...new Set(teacherClasses.map(c=>c.school).filter(Boolean))];
  const filterClasses=teacherClasses.filter(c=>(!schoolFilter||c.school===schoolFilter)&&(!levelFilter||levelFilter==="Semua"||c.educationLevel===levelFilter));
  const visible=comics.filter(c=>{
    const assigned=Array.isArray(c.assignedClassIds)&&c.assignedClassIds.length?c.assignedClassIds:null;
    const classOk=!classFilter || (assigned ? assigned.includes(classFilter) : (c.classId===classFilter || c.school===teacherClasses.find(x=>x.id===classFilter)?.school));
    return String(c.title||"").toLowerCase().includes(search.toLowerCase()) && (statusFilter==="Semua"||c.status===statusFilter) && (levelFilter==="Semua"||(c.educationLevel||"SMA")===levelFilter) && (!schoolFilter||c.school===schoolFilter) && classOk;
  });
  function openCreate(){
    const first=teacherClasses[0];
    setForm({...EMPTY_FORM,educationLevel:first?.educationLevel||session?.educationLevel||"SMA",grade:first?.grade||session?.grade||"X",classId:first?.id||"",className:first?.rombel||"X 1",school:first?.school||session?.school||""});
    setOpen(true);
  }
  function chooseLevel(level){const first=teacherClasses.find(c=>c.educationLevel===level);setForm(f=>({...f,educationLevel:level,grade:first?.grade||(level==="SMP"?"VII":"X"),classId:first?.id||"",className:first?.rombel||(level==="SMP"?"VII 1":"X 1"),school:first?.school||f.school||session?.school||""}));}
  function chooseClass(id){const c=teacherClasses.find(x=>x.id===id);if(!c)return;setForm(f=>({...f,classId:c.id,school:c.school||"",educationLevel:c.educationLevel,grade:c.grade,className:c.rombel}));}
  function submit(e){e.preventDefault();if(!form.title.trim()||!form.classId)return;const c=teacherClasses.find(x=>x.id===form.classId);onCreate({...form,school:c?.school||form.school,grade:c?.grade||form.grade,rombel:c?.rombel||form.className,assignedClassIds:[form.classId]});setOpen(false);}
  return <div>
    <div className="page-kicker">Content Management</div><h1 className="page-title">Kelola E-Comic</h1><p className="page-desc">Materi dibuat untuk ruang kelas tertentu agar konten, siswa, analitik, dan evaluasi tetap terhubung.</p>
    <div className="toolbar"><div className="toolbar-left" style={{flexWrap:"wrap"}}><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari E-Comic..."/><select value={levelFilter} onChange={e=>{setLevelFilter(e.target.value);setSchoolFilter("");setClassFilter("")}} style={{width:140}}><option>Semua</option><option>SMP</option><option>SMA</option></select><select value={schoolFilter} onChange={e=>{setSchoolFilter(e.target.value);setClassFilter("")}} style={{width:220}}><option value="">Semua sekolah</option>{schools.map(s=><option key={s}>{s}</option>)}</select><select value={classFilter} onChange={e=>setClassFilter(e.target.value)} style={{width:180}}><option value="">Semua kelas/rombel</option>{filterClasses.map(c=><option value={c.id} key={c.id}>{c.grade} {c.rombel}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} style={{width:140}}><option>Semua</option><option>Published</option><option>Draft</option></select></div><button className="btn-primary" onClick={openCreate} disabled={!teacherClasses.length}>+ Buat E-Comic</button></div>
    {!teacherClasses.length&&<div className="card empty-state" style={{marginBottom:16}}><strong>Belum ada kelas.</strong><span>Buat kelas terlebih dahulu di Kelas Saya agar E-Comic dapat ditautkan ke sekolah dan rombel.</span></div>}
    <div className="card-grid">{visible.map(comic=><ComicCard key={comic.id} comic={comic} teacher onOpen={id=>navigate("comic-preview",id)} onEdit={onEdit}/>) }{visible.length===0&&<div className="card empty" style={{gridColumn:"1/-1"}}>Belum ada E-Comic yang sesuai filter.</div>}</div>
    {open&&<div className="modal-wrap"><form className="modal" onSubmit={submit}><div className="modal-head"><div><div className="page-kicker">New Content</div><h2>Buat E-Comic</h2></div><button type="button" className="close" onClick={()=>setOpen(false)}>×</button></div>
      <div className="field"><label className="label">Judul</label><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="field"><label className="label">Deskripsi</label><textarea rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><div className="field"><label className="label">Jenjang</label><select value={form.educationLevel} onChange={e=>chooseLevel(e.target.value)}><option>SMP</option><option>SMA</option></select></div><div className="field"><label className="label">Sekolah</label><select value={form.school} onChange={e=>{const c=teacherClasses.find(x=>x.school===e.target.value);setForm(f=>({...f,school:e.target.value,classId:c?.id||f.classId,grade:c?.grade||f.grade,className:c?.rombel||f.className}))}}>{schools.map(s=><option key={s}>{s}</option>)}</select></div></div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><div className="field"><label className="label">Kelas</label><select value={form.grade} onChange={e=>{const c=teacherClasses.find(x=>x.school===form.school&&x.grade===e.target.value);setForm(f=>({...f,grade:e.target.value,classId:c?.id||f.classId,className:c?.rombel||f.className}))}}>{[...new Set(teacherClasses.filter(c=>c.school===form.school).map(c=>c.grade))].map(g=><option key={g}>{g}</option>)}</select></div><div className="field"><label className="label">Kelas/Rombel</label><select value={form.classId} onChange={e=>chooseClass(e.target.value)}>{teacherClasses.filter(c=>c.school===form.school&&c.grade===form.grade).map(c=><option value={c.id} key={c.id}>{c.grade} {c.rombel}</option>)}</select></div></div>
      <div className="field"><label className="label">Materi</label><input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></div><div className="field"><label className="label">Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Draft</option><option>Published</option></select></div><ConceptPicker value={form.concepts} onChange={concepts=>setForm({...form,concepts})} label="Konsep E-Comic"/><div className="actions"><button type="button" className="btn" onClick={()=>setOpen(false)}>Batal</button><button className="btn-primary">Buat & Buka Editor</button></div>
    </form></div>}
  </div>;
}
