import React, { useMemo, useState } from "react";
import EquationEditor from "../../components/common/EquationEditor";
import katex from "katex";
import "katex/dist/katex.min.css";
import { listConcepts } from "../../services/conceptService";
import ConceptPicker from "../../components/common/ConceptPicker";

const emptyQuestion = { id:"", question:"", equation:"", options:["","","",""], answer:0, explanation:"", conceptId:"", level:1, educationLevel:"SMA", grade:"X", classId:"", className:"", school:"", status:"Published" };

export default function QuestionBankPage({ questions=[], teacherClasses=[], session, onSave, onDelete }) {
  const [editing,setEditing]=useState(null);
  const [concepts,setConcepts]=useState([]);
  React.useEffect(()=>{let alive=true;listConcepts().then(items=>alive&&setConcepts(items));return()=>{alive=false}},[]);
  const conceptMap=useMemo(()=>Object.fromEntries(concepts.map(c=>[c.id,c])),[concepts]);
  const [filter,setFilter]=useState("Semua");
  const visible=useMemo(()=>questions.filter(q=>filter==="Semua"||q.educationLevel===filter),[questions,filter]);
  function openNew(){const c=teacherClasses[0];setEditing({...emptyQuestion,id:`q-${Date.now()}`,classId:c?.id||"",className:c?.rombel||"",school:c?.school||session?.school||"",educationLevel:c?.educationLevel||"SMA",grade:c?.grade||"X"});}
  function save(){
    if(!editing.question.trim() || editing.options.some(o=>!o.trim())) return;
    onSave({...editing,question:editing.question.trim(),options:editing.options.map(o=>o.trim()),difficulty:Number(editing.level||1),misconceptionTags:editing.misconceptionTags||["UNCLASSIFIED"],assignedClassIds:editing.classId?[editing.classId]:[]});
    setEditing(null);
  }
  return <div>
    <div className="page-kicker">Content Management</div><h1 className="page-title">Bank Soal</h1><p className="page-desc">Guru dapat membuat soal adaptif lengkap dengan persamaan matematika, konsep, jenjang, dan tingkat kesulitan.</p>
    <div className="toolbar"><select value={filter} onChange={e=>setFilter(e.target.value)} style={{width:160}}><option>Semua</option><option>SMP</option><option>SMA</option></select><select value={""} onChange={()=>{}} style={{width:220}} disabled={!teacherClasses.length}><option>{teacherClasses.length?`Kelas dikelola: ${teacherClasses.length}`:"Belum ada kelas"}</option></select><button className="btn-primary" onClick={openNew}>+ Tambah Soal</button></div>
    <div className="card-grid">{visible.map((q,i)=><div className="card" key={q.id}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><span className="badge badge-blue">{q.educationLevel} · {q.grade}</span><span className="badge badge-amber">Level {q.level}</span></div><h3 style={{marginTop:12}}>Soal {i+1}</h3><p>{q.question}</p>{q.equation&&<div className="equation-preview" dangerouslySetInnerHTML={{__html:renderEquation(q.equation)}}/>}<div className="subtle" style={{marginTop:8}}>{q.conceptId||"Belum dipetakan"} · {conceptMap[q.conceptId]?.name||q.conceptId||"-"}</div><div className="actions"><button className="btn" onClick={()=>setEditing({...q})}>Edit</button><button className="btn" onClick={()=>onDelete(q.id)}>Hapus</button></div></div>)}{visible.length===0&&<div className="card empty" style={{gridColumn:"1/-1"}}>Belum ada soal. Tambahkan soal pertama untuk mulai membangun adaptive question bank.</div>}</div>
    {editing&&<div className="modal-wrap"><div className="modal" style={{maxWidth:760}}><div className="modal-head"><div><div className="page-kicker">Question Authoring</div><h2>{editing.id?.startsWith("q-")?"Tambah Soal":"Edit Soal"}</h2></div><button className="close" onClick={()=>setEditing(null)}>×</button></div>
      <div className="register-grid"><div className="field"><label className="label">Jenjang</label><select value={editing.educationLevel} onChange={e=>setEditing({...editing,educationLevel:e.target.value,grade:e.target.value==="SMP"?"VII":"X"})}><option>SMP</option><option>SMA</option></select></div><div className="field"><label className="label">Kelas</label><select value={editing.grade} onChange={e=>setEditing({...editing,grade:e.target.value})}>{(editing.educationLevel==="SMP"?["VII","VIII","IX"]:["X","XI","XII"]).map(g=><option key={g}>{g}</option>)}</select></div></div>
      <div className="register-grid"><div className="field"><label className="label">Sekolah</label><select value={editing.school||""} onChange={e=>{const c=teacherClasses.find(x=>x.school===e.target.value);setEditing({...editing,school:e.target.value,classId:c?.id||editing.classId,educationLevel:c?.educationLevel||editing.educationLevel,grade:c?.grade||editing.grade,className:c?.rombel||editing.className})}}>{teacherClasses.map(c=><option key={c.school}>{c.school}</option>)}</select></div><div className="field"><label className="label">Kelas/Rombel</label><select value={editing.classId||""} onChange={e=>{const c=teacherClasses.find(x=>x.id===e.target.value);setEditing({...editing,classId:c?.id||"",school:c?.school||editing.school,educationLevel:c?.educationLevel||editing.educationLevel,grade:c?.grade||editing.grade,className:c?.rombel||""})}}>{teacherClasses.map(c=><option key={c.id} value={c.id}>{c.school} · {c.grade} {c.rombel}</option>)}</select></div></div><div className="field"><label className="label">Pertanyaan</label><textarea rows="3" value={editing.question} onChange={e=>setEditing({...editing,question:e.target.value})} placeholder="Contoh: Hasil dari ... adalah ..."/></div>
      <EquationEditor value={editing.equation} onChange={v=>setEditing({...editing,equation:v})} label="Persamaan soal (opsional)"/>
      <div className="field"><label className="label">Pilihan jawaban</label>{editing.options.map((o,i)=><div key={i} style={{display:"flex",gap:8,marginBottom:8}}><button type="button" className={`equation-chip ${editing.answer===i?"selected":""}`} onClick={()=>setEditing({...editing,answer:i})}>{String.fromCharCode(65+i)}</button><input value={o} onChange={e=>setEditing({...editing,options:editing.options.map((x,j)=>j===i?e.target.value:x)})} placeholder={`Pilihan ${String.fromCharCode(65+i)}`}/></div>)}</div>
      <div className="register-grid"><div><ConceptPicker value={editing.conceptId?[editing.conceptId]:[]} onChange={ids=>setEditing({...editing,conceptId:ids[0]||""})} label="Konsep" required /></div><div className="field"><label className="label">Level kesulitan</label><select value={editing.level} onChange={e=>setEditing({...editing,level:Number(e.target.value)})}><option value={1}>Level 1 · Dasar</option><option value={2}>Level 2 · Menengah</option><option value={3}>Level 3 · Lanjutan</option></select></div></div>
      <div className="register-grid"><div className="field"><label className="label">Status</label><select value={editing.status||"Published"} onChange={e=>setEditing({...editing,status:e.target.value})}><option>Draft</option><option>Published</option></select></div><div className="field"><label className="label">Tag miskonsepsi</label><input value={(editing.misconceptionTags||[]).join(", ")} onChange={e=>setEditing({...editing,misconceptionTags:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})} placeholder="EXPONENT_AS_MULTIPLICATION"/></div></div><div className="field"><label className="label">Pembahasan</label><textarea rows="3" value={editing.explanation} onChange={e=>setEditing({...editing,explanation:e.target.value})}/></div>
      <div className="actions"><button className="btn" onClick={()=>setEditing(null)}>Batal</button><button className="btn-primary" onClick={save}>Simpan Soal</button></div>
    </div></div>}
  </div>;
}
function renderEquation(value){try{return katex.renderToString(value,{displayMode:true,throwOnError:false})}catch{return value}}
