import React,{useEffect,useMemo,useState} from "react";
import Badge from "../../components/common/Badge";
import { createClassAccessCode, deactivateClassAccessCode, listClassAccessCodes, saveKnowledgeItem, deleteKnowledgeItem, listKnowledgeItems } from "../../services/learningDataService";
import { concepts as builtinConcepts } from "../../data/demoData";

export function TeacherQuestionProgress({questions=[],attempts=[]}){
 const stats=new Map(); attempts.forEach(a=>{const s=stats.get(a.questionId)||{n:0,c:0};s.n++;if(a.correct)s.c++;stats.set(a.questionId,s)});
 return <div><div className="page-kicker">Item Analytics</div><h1 className="page-title">Progress per Soal</h1><p className="page-desc">Tingkat keberhasilan dihitung dari attempt siswa, bukan data contoh.</p><div className="card"><table className="table"><thead><tr><th>Soal</th><th>Konsep</th><th>Level</th><th>Attempt</th><th>Benar</th><th>Status</th></tr></thead><tbody>{questions.map((q,i)=>{const s=stats.get(q.id)||{n:0,c:0};const pct=s.n?Math.round(s.c/s.n*100):0;return <tr key={q.id}><td><strong>Soal {i+1}</strong><div className="subtle">{q.question}</div></td><td>{q.conceptId}</td><td>{q.level||q.difficulty||1}</td><td>{s.n}</td><td>{pct}%</td><td><Badge tone={pct>=80?"green":pct>=50?"blue":"amber"}>{s.n===0?"Belum dikerjakan":pct>=80?"Baik":"Perlu ditinjau"}</Badge></td></tr>})}</tbody></table>{!questions.length&&<div className="empty-state"><strong>Belum ada bank soal.</strong></div>}</div></div>
}

export function TeacherRanking({students=[]}){const rows=students.slice().sort((a,b)=>(b.xp||0)-(a.xp||0));return <div><div className="page-kicker">Class Ranking</div><h1 className="page-title">Peringkat Siswa</h1><p className="page-desc">Urutan berdasarkan XP siswa pada data yang tersedia.</p><div className="card">{rows.length?<table className="table"><thead><tr><th>#</th><th>Siswa</th><th>Kelas</th><th>Mastery</th><th>XP</th></tr></thead><tbody>{rows.map((s,i)=><tr key={s.uid||i}><td><strong>{i+1}</strong></td><td>{s.name}</td><td>{s.grade||"-"} {s.rombel||""}</td><td>{s.mastery||0}%</td><td>{s.xp||0}</td></tr>)}</tbody></table>:<div className="empty-state"><strong>Belum ada siswa.</strong><span>Peringkat akan terisi setelah akun siswa aktif.</span></div>}</div></div>}

export function TeacherExamTimes({examResults=[],students=[]}){const names=new Map(students.map(s=>[s.uid,s.name]));return <div><div className="page-kicker">Exam Monitoring</div><h1 className="page-title">Jawaban & Waktu Ujian</h1><p className="page-desc">Rekap hasil, durasi, dan waktu pengerjaan ujian siswa.</p><div className="card">{examResults.length?<table className="table"><thead><tr><th>Siswa</th><th>Nilai</th><th>Benar</th><th>Durasi</th><th>Waktu</th></tr></thead><tbody>{examResults.map(r=><tr key={r.id}><td>{names.get(r.uid)||r.name||r.uid}</td><td><strong>{r.score}</strong></td><td>{r.correct}/{r.total}</td><td>{Math.round((r.durationSeconds||0)/60)} menit</td><td>{r.createdAt?new Date(r.createdAt).toLocaleString("id-ID"):"-"}</td></tr>)}</tbody></table>:<div className="empty-state"><strong>Belum ada hasil ujian.</strong><span>Rekap akan muncul setelah siswa menyelesaikan ujian.</span></div>}</div></div>}

export function TeacherReflections({reflections=[],students=[]}){const names=new Map(students.map(s=>[s.uid,s.name]));return <div><div className="page-kicker">Student Voice</div><h1 className="page-title">Refleksi Siswa</h1><p className="page-desc">Baca refleksi siswa untuk melihat pemahaman dan kesulitan yang mereka rasakan.</p><div className="card">{reflections.length?reflections.map(r=><div className="list-item" key={r.id}><div><strong>{names.get(r.uid)||r.name||"Siswa"}</strong><div className="subtle">{r.createdAt?new Date(r.createdAt).toLocaleString("id-ID"):"-"}</div><p style={{margin:"6px 0 0"}}>{r.text}</p></div></div>):<div className="empty-state"><strong>Belum ada refleksi siswa.</strong><span>Akan muncul setelah siswa mengirim refleksi.</span></div>}</div></div>}

export function TeacherAccess({session}){
 const [codes,setCodes]=useState([]);const [selected,setSelected]=useState({educationLevel:session?.educationLevel||"SMA",grade:session?.grade||"X",rombel:session?.rombel||"1"});
 async function refresh(){setCodes(await listClassAccessCodes(session?.uid));}
 useEffect(()=>{refresh()},[session?.uid]);
 async function create(){await createClassAccessCode({teacherUid:session?.uid,teacherName:session?.name,school:session?.school||"",...selected});await refresh();}
 async function disable(id){await deactivateClassAccessCode(id);await refresh();}
 return <div><div className="page-kicker">Class Access</div><h1 className="page-title">Kode Akses Kelas</h1><p className="page-desc">Buat kode kelas untuk membagikan ruang belajar tertentu kepada siswa.</p><div className="card"><div className="register-grid"><div><label className="label">Jenjang</label><select value={selected.educationLevel} onChange={e=>setSelected({...selected,educationLevel:e.target.value,grade:e.target.value==="SMP"?"VII":"X"})}><option>SMP</option><option>SMA</option></select></div><div><label className="label">Kelas</label><select value={selected.grade} onChange={e=>setSelected({...selected,grade:e.target.value})}>{(selected.educationLevel==="SMP"?["VII","VIII","IX"]:["X","XI","XII"]).map(x=><option key={x}>{x}</option>)}</select></div><div><label className="label">Rombel</label><select value={selected.rombel} onChange={e=>setSelected({...selected,rombel:e.target.value})}>{Array.from({length:12},(_,i)=>String(i+1)).map(x=><option key={x}>{x}</option>)}</select></div></div><button className="btn-primary" style={{marginTop:12}} onClick={create}>+ Buat Kode Akses</button></div><div className="card" style={{marginTop:16}}><h2>Kode Aktif</h2>{codes.length?codes.map(c=><div className="list-item" key={c.id}><div><strong>{c.code}</strong><div className="subtle">{c.educationLevel} · {c.grade} {c.rombel} · {c.school||"Semua sekolah"}</div></div><button className="btn" onClick={()=>disable(c.id)}>{c.active?"Nonaktifkan":"Aktif"}</button></div>):<div className="empty-state"><strong>Belum ada kode kelas.</strong></div>}</div></div>
}

export function TeacherAttendance({records=[],students=[]}){const names=new Map(students.map(s=>[s.uid,s.name]));return <div><div className="page-kicker">Class Attendance</div><h1 className="page-title">Presensi</h1><p className="page-desc">Pantau kehadiran siswa berdasarkan catatan presensi.</p><div className="card">{records.length?<table className="table"><thead><tr><th>Tanggal</th><th>Siswa</th><th>Kelas</th><th>Status</th><th>Waktu</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{r.date}</td><td>{names.get(r.uid)||r.name||r.uid}</td><td>{r.grade||"-"} {r.rombel||""}</td><td><Badge tone="green">{r.status}</Badge></td><td>{r.checkInAt?new Date(r.checkInAt).toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"}):"-"}</td></tr>)}</tbody></table>:<div className="empty-state"><strong>Belum ada presensi.</strong><span>Catatan kehadiran siswa akan tampil di sini.</span></div>}</div></div>}

export function TeacherKnowledge(){
 const [items,setItems]=useState([]);const [editing,setEditing]=useState(null);const [type,setType]=useState("concept");
 async function refresh(){setItems(await listKnowledgeItems())} useEffect(()=>{refresh()},[]);
 function start(){setEditing({id:`kb-${Date.now()}`,type,title:"",content:"",conceptId:"E1",prerequisiteIds:""});}
 async function save(){if(!editing.title.trim())return;await saveKnowledgeItem({...editing,prerequisiteIds:editing.prerequisiteIds.split(",").map(x=>x.trim()).filter(Boolean)});setEditing(null);await refresh();}
 return <div><div className="page-kicker">Knowledge Base</div><h1 className="page-title">Knowledge Base</h1><p className="page-desc">Kelola konteks yang dapat dipakai AI Tutor: konsep, definisi, contoh, sumber, dan prasyarat.</p><div className="toolbar"><select value={type} onChange={e=>setType(e.target.value)}><option value="concept">Konsep</option><option value="source">Sumber Materi</option></select><button className="btn-primary" onClick={start}>+ Tambah Item</button></div><div className="card-grid">{items.map(i=><div className="card" key={i.id}><Badge tone="blue">{i.type}</Badge><h3>{i.title}</h3><p className="subtle">{i.content}</p><div className="actions"><button className="btn" onClick={()=>setEditing(i)}>Edit</button><button className="btn" onClick={async()=>{await deleteKnowledgeItem(i.id);refresh()}}>Hapus</button></div></div>)}<div className="card"><h2>Konsep bawaan</h2><div className="list">{Object.values(builtinConcepts).map(c=><div className="list-item" key={c.id}><strong>{c.id} · {c.name}</strong><span>{c.prerequisiteIds?.join(", ")||"-"}</span></div>)}</div></div></div>{editing&&<div className="modal-wrap"><div className="modal"><div className="modal-head"><div><div className="page-kicker">Knowledge Authoring</div><h2>{editing.id.startsWith("kb-")?"Tambah Item":"Edit Item"}</h2></div><button className="close" onClick={()=>setEditing(null)}>×</button></div><div className="field"><label className="label">Judul</label><input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></div><div className="field"><label className="label">Isi / Definisi / Sumber</label><textarea rows="6" value={editing.content} onChange={e=>setEditing({...editing,content:e.target.value})}/></div>{editing.type==="concept"&&<div className="field"><label className="label">Konsep</label><select value={editing.conceptId} onChange={e=>setEditing({...editing,conceptId:e.target.value})}>{Object.values(builtinConcepts).map(c=><option key={c.id}>{c.id}</option>)}</select></div>}<div className="actions"><button className="btn" onClick={()=>setEditing(null)}>Batal</button><button className="btn-primary" onClick={save}>Simpan</button></div></div></div>}</div>
}
