import React,{useEffect,useMemo,useState} from "react";
import Badge from "../../components/common/Badge";
import { saveKnowledgeItem, deleteKnowledgeItem, listKnowledgeItems } from "../../services/learningDataService";
import { createTeacherClass, listClassesForTeacher, setTeacherClassActive, setTeacherClassEnrollment, deleteTeacherClass } from "../../services/accessControlService";
import { classLabel, canonicalRombel } from "../../utils/classLabel";
import { saveConcept, removeConcept } from "../../services/conceptService";

export function TeacherQuestionProgress({questions=[],attempts=[]}){
 const stats=new Map(); attempts.forEach(a=>{const s=stats.get(a.questionId)||{n:0,c:0};s.n++;if(a.correct)s.c++;stats.set(a.questionId,s)});
 return <div><div className="page-kicker">Item Analytics</div><h1 className="page-title">Progress per Soal</h1><p className="page-desc">Tingkat keberhasilan dihitung dari attempt siswa, bukan data contoh.</p><div className="card"><table className="table"><thead><tr><th>Soal</th><th>Konsep</th><th>Level</th><th>Attempt</th><th>Benar</th><th>Status</th></tr></thead><tbody>{questions.map((q,i)=>{const s=stats.get(q.id)||{n:0,c:0};const pct=s.n?Math.round(s.c/s.n*100):0;return <tr key={q.id}><td><strong>Soal {i+1}</strong><div className="subtle">{q.question}</div></td><td>{q.conceptId}</td><td>{q.level||q.difficulty||1}</td><td>{s.n}</td><td>{pct}%</td><td><Badge tone={pct>=80?"green":pct>=50?"blue":"amber"}>{s.n===0?"Belum dikerjakan":pct>=80?"Baik":"Perlu ditinjau"}</Badge></td></tr>})}</tbody></table>{!questions.length&&<div className="empty-state"><strong>Belum ada bank soal.</strong></div>}</div></div>
}

export function TeacherRanking({students=[]}){const rows=students.slice().sort((a,b)=>(b.xp||0)-(a.xp||0));return <div><div className="page-kicker">Class Ranking</div><h1 className="page-title">Peringkat Siswa</h1><p className="page-desc">Urutan berdasarkan XP siswa pada data yang tersedia.</p><div className="card">{rows.length?<table className="table"><thead><tr><th>#</th><th>Siswa</th><th>Kelas</th><th>Mastery</th><th>XP</th></tr></thead><tbody>{rows.map((s,i)=><tr key={s.uid||i}><td><strong>{i+1}</strong></td><td>{s.name}</td><td>{classLabel(s.grade, s.rombel)}</td><td>{s.mastery||0}%</td><td>{s.xp||0}</td></tr>)}</tbody></table>:<div className="empty-state"><strong>Belum ada siswa.</strong><span>Peringkat akan terisi setelah akun siswa aktif.</span></div>}</div></div>}

export function TeacherExamTimes({examResults=[],students=[]}){const names=new Map(students.map(s=>[s.uid,s.name]));return <div><div className="page-kicker">Exam Monitoring</div><h1 className="page-title">Jawaban & Waktu Ujian</h1><p className="page-desc">Rekap hasil, durasi, dan waktu pengerjaan ujian siswa.</p><div className="card">{examResults.length?<table className="table"><thead><tr><th>Siswa</th><th>Nilai</th><th>Benar</th><th>Durasi</th><th>Waktu</th></tr></thead><tbody>{examResults.map(r=><tr key={r.id}><td>{names.get(r.uid)||r.name||r.uid}</td><td><strong>{r.score}</strong></td><td>{r.correct}/{r.total}</td><td>{Math.round((r.durationSeconds||0)/60)} menit</td><td>{r.createdAt?new Date(r.createdAt).toLocaleString("id-ID"):"-"}</td></tr>)}</tbody></table>:<div className="empty-state"><strong>Belum ada hasil ujian.</strong><span>Rekap akan muncul setelah siswa menyelesaikan ujian.</span></div>}</div></div>}

export function TeacherAttendance({records=[],students=[]}){
 const names=new Map(students.map(s=>[s.uid,s.name]));
 const rows=Array.isArray(records)?records:[];
 return <div><div className="page-kicker">Class Attendance</div><h1 className="page-title">Presensi Siswa</h1><p className="page-desc">Rekap presensi siswa pada kelas yang dikelola guru.</p><div className="card">{rows.length?<table className="table"><thead><tr><th>Siswa</th><th>Tanggal</th><th>Status</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}><td>{names.get(r.uid)||r.name||r.uid||"Siswa"}</td><td>{r.date||r.createdAt?new Date(r.date||r.createdAt).toLocaleDateString("id-ID"):"-"}</td><td><Badge tone={r.status==="hadir"?"green":r.status==="izin"?"blue":"amber"}>{r.status||"-"}</Badge></td></tr>)}</tbody></table>:<div className="empty-state"><strong>Belum ada data presensi.</strong><span>Presensi akan muncul setelah siswa mengisi kehadiran.</span></div>}</div></div>
}

export function TeacherReflections({reflections=[],students=[]}){const names=new Map(students.map(s=>[s.uid,s.name]));return <div><div className="page-kicker">Student Voice</div><h1 className="page-title">Refleksi Siswa</h1><p className="page-desc">Baca refleksi siswa untuk melihat pemahaman dan kesulitan yang mereka rasakan.</p><div className="card">{reflections.length?reflections.map(r=><div className="list-item" key={r.id}><div><strong>{names.get(r.uid)||r.name||"Siswa"}</strong><div className="subtle">{r.createdAt?new Date(r.createdAt).toLocaleString("id-ID"):"-"}</div><p style={{margin:"6px 0 0"}}>{r.text}</p></div></div>):<div className="empty-state"><strong>Belum ada refleksi siswa.</strong><span>Akan muncul setelah siswa mengirim refleksi.</span></div>}</div></div>}

export function TeacherAccess({session,onClassesChange}){
 const [classes,setClasses]=useState([]);
 const [selected,setSelected]=useState({educationLevel:session?.educationLevel||"SMA",grade:session?.grade||"X",rombel:canonicalRombel(session?.grade||"X", session?.rombel||"1")});
 async function refresh(){const rows=await listClassesForTeacher(session?.uid);setClasses(rows);onClassesChange?.(rows);}
 useEffect(()=>{refresh()},[session?.uid]);
 async function create(){try{await createTeacherClass(session,selected);await refresh();}catch(e){alert(e?.message||"Gagal membuat kelas.");}}
 async function toggleActive(c){try{await setTeacherClassActive(c.id,c.active===false);await refresh();}catch(e){alert(e?.message||"Gagal mengubah status kelas.");}}
 async function toggleEnrollment(c){try{await setTeacherClassEnrollment(c.id,c.enrollmentOpen===false);await refresh();}catch(e){alert(e?.message||"Gagal mengubah status pendaftaran.");}}
 async function remove(c){if(!window.confirm(`Hapus kelas ${classLabel(c.grade,c.rombel)}?\n\nSiswa yang sudah terhubung tidak otomatis dihapus.`))return;try{await deleteTeacherClass(c.id);await refresh();}catch(e){alert(e?.message||"Gagal menghapus kelas.");}}
 return <div><div className="page-kicker">Class Management</div><h1 className="page-title">Kelas Saya</h1><p className="page-desc">Guru hanya mengelola kelas yang dibuat atas akunnya. Siswa yang memilih sekolah, tingkat, dan rombel yang sama akan otomatis terhubung ke Guru kelas ini saat mendaftar.</p><div className="card"><div className="register-grid"><div><label className="label">Jenjang</label><select value={selected.educationLevel} onChange={e=>setSelected({...selected,educationLevel:e.target.value,grade:e.target.value==="SMP"?"VII":"X",rombel:`${e.target.value==="SMP"?"VII":"X"} 1`})}><option>SMP</option><option>SMA</option></select></div><div><label className="label">Tingkat</label><select value={selected.grade} onChange={e=>setSelected({...selected,grade:e.target.value,rombel:`${e.target.value} 1`})}>{(selected.educationLevel==="SMP"?["VII","VIII","IX"]:["X","XI","XII"]).map(x=><option key={x}>{x}</option>)}</select></div><div><label className="label">Rombel</label><select value={selected.rombel} onChange={e=>setSelected({...selected,rombel:e.target.value})}>{Array.from({length:12},(_,i)=>`${selected.grade} ${i+1}`).map(x=><option key={x}>{x}</option>)}</select></div></div><button className="btn-primary" style={{marginTop:12}} onClick={create}>+ Buat Kelas</button></div><div className="card" style={{marginTop:16}}><div className="section-head"><div><h2>Kelas yang Saya Kelola</h2><span>Aktif/nonaktif dan pendaftaran dapat diatur per kelas.</span></div></div>{classes.length?classes.map(c=>{const active=c.active!==false;const open=c.enrollmentOpen!==false;return <div className="list-item" key={c.id}><div style={{minWidth:0,flex:1}}><strong>{classLabel(c.grade, c.rombel)}</strong><div className="subtle">{c.school} · {c.educationLevel} · {active?"Kelas aktif":"Kelas nonaktif"} · {open&&active?"Pendaftaran terbuka":"Pendaftaran ditutup"}</div></div><div className="actions" style={{flexWrap:"wrap",justifyContent:"flex-end"}}><button className="btn" onClick={()=>toggleActive(c)}>{active?"Nonaktifkan":"Aktifkan"}</button><button className="btn" disabled={!active} onClick={()=>toggleEnrollment(c)}>{open?"Tutup pendaftaran":"Buka pendaftaran"}</button><button className="btn" onClick={()=>remove(c)}>Hapus</button></div></div>}) : <div className="empty-state"><strong>Belum ada kelas.</strong><span>Buat kelas pertama agar siswa dapat otomatis terhubung.</span></div>}</div></div>
}

export function TeacherKnowledge(){
 const [items,setItems]=useState([]);const [editing,setEditing]=useState(null);const [type,setType]=useState("concept");const [error,setError]=useState("");
 async function refresh(){setItems(await listKnowledgeItems())}
 useEffect(()=>{refresh()},[]);
 function start(){setError("");setEditing(type==="concept"?{id:"",type:"concept",conceptId:"",title:"",content:"",prerequisiteIds:[]}:{id:`kb-${Date.now()}`,type:"source",title:"",content:"",prerequisiteIds:[]});}
 async function save(){setError("");try{if(editing.type==="concept"){await saveConcept({id:editing.conceptId,title:editing.title,content:editing.content,prerequisiteIds:editing.prerequisiteIds});}else{if(!editing.title.trim())throw new Error("Judul wajib diisi.");await saveKnowledgeItem({...editing,prerequisiteIds:[]});}setEditing(null);await refresh();}catch(e){setError(e?.message||"Gagal menyimpan.");}}
 async function remove(id,typeValue){if(!window.confirm("Hapus item ini?"))return;if(typeValue==="concept")await removeConcept(id);else await deleteKnowledgeItem(id);await refresh();}
 const concepts=items.filter(i=>i.type==="concept").sort((a,b)=>String(a.conceptId||a.id).localeCompare(String(b.conceptId||b.id),undefined,{numeric:true}));
 const sources=items.filter(i=>i.type!=="concept");
 return <div><div className="page-kicker">Knowledge Base</div><h1 className="page-title">Knowledge Base</h1><p className="page-desc">Kelola konsep dan sumber yang menjadi referensi AI Tutor. Konsep di sini menjadi daftar resmi yang tersedia untuk pemetaan E-Comic, bank soal, dan pembelajaran adaptif.</p>
 <div className="toolbar"><select value={type} onChange={e=>setType(e.target.value)}><option value="concept">Konsep</option><option value="source">Sumber Materi</option></select><button className="btn-primary" onClick={start}>+ Tambah {type==="concept"?"Konsep":"Sumber"}</button></div>{error&&<div className="upload-note error">{error}</div>}
 <div className="card" style={{marginTop:16}}><h2>Konsep Pembelajaran</h2><p className="subtle">Daftar konsep sengaja dimulai kosong. Guru menentukan sendiri kode, nama, deskripsi, dan prasyarat.</p>{concepts.length?<div className="list">{concepts.map(c=><div className="list-item" key={c.id}><div><strong>{c.conceptId||c.id} · {c.title||c.name}</strong><div className="subtle">Prasyarat: {(c.prerequisiteIds||[]).join(", ")||"Tidak ada"}</div>{c.content&&<div className="subtle">{c.content}</div>}</div><div className="actions"><button className="btn" onClick={()=>setEditing({id:c.id,type:"concept",conceptId:c.conceptId||c.id,title:c.title||c.name,content:c.content||"",prerequisiteIds:c.prerequisiteIds||[]})}>Edit</button><button className="btn" onClick={()=>remove(c.id,"concept")}>Hapus</button></div></div>)}</div>:<div className="empty-state"><strong>Belum ada konsep.</strong><span>Tambahkan konsep pertama sesuai struktur materi yang kamu inginkan.</span></div>}</div>
 <div className="card" style={{marginTop:16}}><h2>Sumber Materi</h2>{sources.length?sources.map(i=><div className="list-item" key={i.id}><div><strong>{i.title}</strong><div className="subtle">{i.content}</div></div><div className="actions"><button className="btn" onClick={()=>setEditing({...i})}>Edit</button><button className="btn" onClick={()=>remove(i.id,i.type)}>Hapus</button></div></div>):<div className="empty-state"><strong>Belum ada sumber materi.</strong></div>}</div>
 {editing&&<div className="modal-wrap"><div className="modal"><div className="modal-head"><div><div className="page-kicker">Knowledge Authoring</div><h2>{editing.type==="concept"?(editing.id?"Edit Konsep":"Tambah Konsep"):"Sumber Materi"}</h2></div><button className="close" onClick={()=>setEditing(null)}>×</button></div>
 {editing.type==="concept"?<><div className="field"><label className="label">Kode Konsep</label><input value={editing.conceptId} onChange={e=>setEditing({...editing,conceptId:e.target.value.toUpperCase().replace(/\s+/g,"-")})} placeholder="Contoh: E1, GEO-01, TRIG-A"/></div><div className="field"><label className="label">Nama Konsep</label><input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})} placeholder="Nama konsep"/></div><div className="field"><label className="label">Deskripsi / definisi</label><textarea rows="5" value={editing.content} onChange={e=>setEditing({...editing,content:e.target.value})}/></div><div className="field"><label className="label">Kode prasyarat</label><input value={(editing.prerequisiteIds||[]).join(", ")} onChange={e=>setEditing({...editing,prerequisiteIds:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})} placeholder="E1, E2"/><div className="subtle">Kosongkan jika tidak memiliki prasyarat.</div></div></>:<><div className="field"><label className="label">Judul</label><input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></div><div className="field"><label className="label">Isi / Sumber</label><textarea rows="7" value={editing.content} onChange={e=>setEditing({...editing,content:e.target.value})}/></div></>}
 <div className="actions"><button className="btn" onClick={()=>setEditing(null)}>Batal</button><button className="btn-primary" onClick={save}>Simpan</button></div></div></div>}
 </div>
}
