import React,{useMemo,useState} from "react";
import { BookOpen, BarChart3, Users, Plus, ArrowRight, Sparkles } from "lucide-react";
import { classLabel } from "../../utils/classLabel";
import { analyzeClassWithAI } from "../../services/tutorService";

export default function TeacherDashboard({state,navigate,students=[],models=[],attempts=[],events=[],session,teacherClasses=[],onRefresh}){
 const [aiResult,setAiResult]=useState(null); const [loading,setLoading]=useState(false);
 const safeStudents=Array.isArray(students)?students:[]; const safeModels=Array.isArray(models)?models:[]; const safeAttempts=Array.isArray(attempts)?attempts:[]; const safeEvents=Array.isArray(events)?events:[]; const safeComics=Array.isArray(state?.comics)?state.comics:[];
 const modelByUid=useMemo(()=>new Map(safeModels.map(m=>[m.uid,m])),[safeModels]);
 const scoped=safeStudents.filter(s=>!session?.uid||s.classTeacherUid===session.uid||teacherClasses.some(c=>c.id===s.classId));
 const rows=scoped.map(s=>({...s,model:modelByUid.get(s.uid)||s.model||{}}));
 const published=safeComics.filter(c=>c.status==="Published").length; const episodes=safeComics.reduce((n,c)=>n+(c.episodes?.length||0),0);
 const avgMastery=rows.length?Math.round(rows.reduce((n,s)=>n+Number(s.model?.overallMastery||0),0)/rows.length*100):0;
 const conceptMap={}; rows.forEach(r=>Object.entries(r.model?.concepts||{}).forEach(([id,p])=>{const x=conceptMap[id]||{values:[],mis:0};x.values.push(Number(p?.mastery||0));x.mis+=(r.model?.misconceptions||[]).filter(m=>m.conceptId===id&&!m.resolved).length;conceptMap[id]=x;}));
 const concepts=Object.entries(conceptMap).map(([id,x])=>({id,value:Math.round(x.values.reduce((a,b)=>a+b,0)/x.values.length*100),mis:x.mis})); const topMastery=concepts.slice().sort((a,b)=>b.value-a.value).slice(0,3); const lowMastery=concepts.slice().sort((a,b)=>a.value-b.value).slice(0,3);
 const misMap={}; rows.forEach(r=>(r.model?.misconceptions||[]).filter(m=>!m.resolved).forEach(m=>{const k=`${m.conceptId||"-"} · ${m.tag||"MISKONSEPSI"}`;misMap[k]=(misMap[k]||0)+1;})); const topMis=Object.entries(misMap).sort((a,b)=>b[1]-a[1]).slice(0,3);
 async function runAI(){setLoading(true);try{setAiResult(await analyzeClassWithAI({classData:{school:session?.school||"",studentCount:rows.length,avgMastery,topMastery:topMastery.map(x=>({id:x.id,value:x.value})),priorityConcepts:lowMastery.map(x=>({id:x.id,value:x.value})),misconceptions:topMis.map(([label,count])=>`${label}: ${count}`),studentNeeds:rows.slice().sort((a,b)=>Number(a.model?.overallMastery||0)-Number(b.model?.overallMastery||0)).slice(0,5).map(s=>`${s.name}: mastery ${Math.round(Number(s.model?.overallMastery||0)*100)}%`)}}));}finally{setLoading(false)}}
 return <div><div className="page-kicker">Teacher Workspace</div><h1 className="page-title">Dashboard Guru</h1><p className="page-desc">Pantau pembelajaran kelas, lihat pola miskonsepsi yang paling urgen, dan gunakan AI untuk menentukan tindak lanjut.</p>
  <div className="stats-row"><div className="ac-stat"><div className="stat-icon purple"><BookOpen/></div><div><span>Total E-Comic</span><strong>{safeComics.length}</strong></div></div><div className="ac-stat"><div className="stat-icon green"><BookOpen/></div><div><span>Published</span><strong>{published}</strong></div></div><div className="ac-stat"><div className="stat-icon orange"><BarChart3/></div><div><span>Rata-rata Mastery</span><strong>{avgMastery}%</strong></div></div><div className="ac-stat"><div className="stat-icon blue"><Users/></div><div><span>Siswa terdaftar</span><strong>{scoped.length}</strong></div></div></div>
  <div className="stats-row" style={{marginTop:12}}><div className="ac-stat"><div className="stat-icon purple">✓</div><div><span>Konsep Unggul</span><strong>{concepts.filter(x=>x.value>=80).length}</strong></div></div><div className="ac-stat"><div className="stat-icon orange">!</div><div><span>Miskonsepsi Aktif</span><strong>{Object.values(misMap).reduce((a,b)=>a+b,0)}</strong></div></div><div className="ac-stat"><div className="stat-icon green">◷</div><div><span>Waktu Belajar</span><strong>{Math.round(safeEvents.reduce((n,e)=>n+((e.type==="app_session"||e.type==="screen_time")?Number(e.durationSeconds||0):0),0)/60)} mnt</strong></div></div><div className="ac-stat"><div className="stat-icon blue">💬</div><div><span>Interaksi Tutor</span><strong>{safeEvents.filter(e=>e.type==="tutor_message").length}</strong></div></div></div>
  <div className="ac-hero"><div className="hero-copy"><span className="hero-label">TEACHER CONTENT STUDIO</span><h2>Buat konten, ukur pemahaman, dan tindak lanjuti kebutuhan siswa.</h2><p>Guru mengatur materi dan soal. AI menganalisis jawaban siswa, miskonsepsi, hint, mastery, dan aktivitas untuk membantu pembelajaran adaptif.</p><div className="hero-buttons"><button className="primary-btn" onClick={()=>navigate("comic-management")}><Plus size={16}/> Kelola E-Comic</button><button className="ghost-btn" onClick={()=>navigate("analytics")}>Lihat Analitik <ArrowRight size={16}/></button></div></div><div className="hero-illustration"><div className="hero-book">📚</div></div></div>
  <div className="analytics-grid" style={{marginTop:18}}><div className="card"><div className="section-head"><div><h2>Top Mastery</h2><span>Konsep yang paling dikuasai secara umum</span></div></div>{topMastery.length?topMastery.map(x=><div className="list-item" key={x.id}><strong>{x.id}</strong><strong>{x.value}%</strong></div>):<div className="empty-state"><strong>Belum ada data mastery.</strong></div>}</div><div className="card"><div className="section-head"><div><h2>Top & Lowest Miskonsepsi</h2><span>Pola kesalahan paling urgen berdasarkan data siswa</span></div></div>{topMis.length?topMis.map(([label,count])=><div className="list-item" key={label}><span>{label}</span><strong>{count}</strong></div>):<div className="empty-state"><strong>Belum ada miskonsepsi aktif.</strong></div>}<div style={{marginTop:12}}>{lowMastery.length&&<><div className="label">Konsep yang perlu ditingkatkan</div>{lowMastery.map(x=><div className="list-item" key={x.id}><span>{x.id}</span><strong>{x.value}%</strong></div>)}</>}</div></div></div>
  <div className="card" style={{marginTop:18}}><div className="section-head"><div><h2>AI Analisis Kelas</h2><span>AI membaca pola kelas dan memberi rekomendasi tindak lanjut.</span></div><Sparkles size={19}/></div><button className="btn-primary" disabled={loading||!rows.length} onClick={runAI}>{loading?"AI sedang menganalisis…":"✨ Analisis pola kelas"}</button>{aiResult&&<div className="ai-feedback" style={{marginTop:12}}><strong>{aiResult.ai===false?"Analisis berbasis data":"Analisis AI"}</strong><p>{aiResult.summary}</p>{aiResult.priorityConcepts?.length>0&&<div><b>Prioritas:</b> {aiResult.priorityConcepts.join("; ")}</div>}{aiResult.recommendations?.map((x,i)=><div className="list-item" key={i}><span>{x}</span></div>)}</div>}</div>
  <div className="card" style={{marginTop:18}}><div className="section-head"><div><h2>Statistik Siswa</h2><span>Ringkasan kemampuan aktual untuk tindak lanjut.</span></div><button className="btn" onClick={onRefresh}>↻ Perbarui</button></div>{rows.length?<table className="table"><thead><tr><th>Siswa</th><th>Kelas</th><th>Mastery</th><th>Attempt</th><th>Miskonsepsi</th></tr></thead><tbody>{rows.map(s=><tr key={s.uid}><td><strong>{s.name}</strong></td><td>{classLabel(s.grade,s.rombel)}</td><td>{Math.round(Number(s.model?.overallMastery||0)*100)}%</td><td>{s.model?.totalAttempts||0}</td><td>{(s.model?.misconceptions||[]).filter(m=>!m.resolved).length}</td></tr>)}</tbody></table>:<div className="empty-state"><strong>Belum ada siswa.</strong><span>Data akan muncul setelah siswa terhubung ke kelas.</span></div>}</div>
 </div>;
}
