import React,{useEffect,useMemo,useRef,useState} from "react";
import { BookOpen, CheckCircle2, ClipboardList, Info, Lightbulb, Maximize2, MessageCircle, Minimize2, PanelRight, PlayCircle, Trash2, TrendingUp, Users, X } from "lucide-react";
import Badge from "../../components/common/Badge";
import { listConcepts } from "../../services/conceptService";
import MediaImage from "../../components/media/MediaImage";
import "katex/dist/katex.min.css";
import katex from "katex";
import AIResponse from "../../components/common/AIResponse";

const tabs=[{id:"tutor",label:"Tutor",icon:MessageCircle},{id:"tokoh",label:"Tokoh",icon:Users},{id:"kuis",label:"Kuis",icon:ClipboardList},{id:"materi",label:"Materi",icon:BookOpen},{id:"progres",label:"Progres",icon:TrendingUp}];
const renderEquation=v=>{if(!v)return null;try{const lines=String(v).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);return lines.map(x=>katex.renderToString(x,{displayMode:true,throwOnError:false})).join("")}catch{return String(v)}};

export default function ComicReaderPage({comic,studentModel,questions=[],navigate,onPanelViewed,onAnswer,onAIExplain,onTutorSend,onClearHistory,tutorMessages=[],readerContext,session}){
 const [ei,setEi]=useState(Number.isInteger(readerContext?.episodeIndex)?readerContext.episodeIndex:0),[pi,setPi]=useState(Number.isInteger(readerContext?.panelIndex)?readerContext.panelIndex:0),[focusMode,setFocusMode]=useState(false),[infoTab,setInfoTab]=useState("tutor"),[quizSelected,setQuizSelected]=useState(null),[quizDiagnosis,setQuizDiagnosis]=useState(null),[tutorInput,setTutorInput]=useState(""),[tutorBusy,setTutorBusy]=useState(false);
 const [concepts,setConcepts]=useState({});
 const tutorMessagesRef=useRef(null);
 useEffect(()=>{let alive=true;listConcepts().then(items=>{if(alive)setConcepts(Object.fromEntries(items.map(c=>[c.id,c])))}).catch(()=>{});return()=>{alive=false}},[]);
 const panelStartedAt=useRef(Date.now());
 const lastPanelRef=useRef({comicId:comic?.id,episodeIndex:0,panelIndex:0});
 const quizStartedAt=useRef(Date.now());
 const episode=comic?.episodes?.[ei],panel=episode?.panels?.[pi];
 const totalPanels=useMemo(()=>comic?.episodes?.reduce((sum,ep)=>sum+(ep.panels?.length||0),0)||0,[comic]);
 const currentGlobalPanel=useMemo(()=>comic?comic.episodes.slice(0,ei).reduce((sum,ep)=>sum+(ep.panels?.length||0),0)+pi+1:0,[comic,ei,pi]);
 const overallProgress=totalPanels?Math.round(currentGlobalPanel/totalPanels*100):0;
 const conceptId=panel?.conceptIds?.[0]; const conceptName=concepts[conceptId]?.name||conceptId||"Konsep pembelajaran"; const mastery=conceptId?studentModel?.concepts?.[conceptId]?.mastery:null;
 const relatedQuestions=useMemo(()=>{const exact=questions.filter(q=>q.comicId===comic?.id && q.panelId===panel?.id);if(exact.length)return exact.slice(0,4);return questions.filter(q=>q.comicId===comic?.id && (!conceptId||q.conceptId===conceptId)).slice(0,4);},[questions,conceptId,comic?.id,panel?.id]);
 const activeQuestion=relatedQuestions[0];
 useEffect(()=>{
   const now=Date.now();
   const prev=lastPanelRef.current;
   const previousDuration=panelStartedAt.current ? Math.floor((now-panelStartedAt.current)/1000) : 0;
   if(prev && prev.comicId===comic?.id && (prev.episodeIndex!==ei || prev.panelIndex!==pi)){
     onPanelViewed?.({comic,episodeIndex:prev.episodeIndex,panelIndex:prev.panelIndex,durationSeconds:previousDuration});
   }
   onPanelViewed?.({comic,episodeIndex:ei,panelIndex:pi,durationSeconds:0});
   lastPanelRef.current={comicId:comic?.id,episodeIndex:ei,panelIndex:pi};
   panelStartedAt.current=now;
   quizStartedAt.current=now;
   setQuizSelected(null);setQuizDiagnosis(null);setTutorInput("");
 },[comic?.id,ei,pi]);
 useEffect(()=>{const el=tutorMessagesRef.current;if(el)requestAnimationFrame(()=>{el.scrollTop=el.scrollHeight;});},[tutorMessages?.length,tutorBusy,infoTab]);
 useEffect(()=>{if(!focusMode)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";const key=e=>{if(e.key==="Escape")setFocusMode(false);if(e.key==="ArrowRight")next();if(e.key==="ArrowLeft")prev();};window.addEventListener("keydown",key);return()=>{document.body.style.overflow=old;window.removeEventListener("keydown",key)};},[focusMode,ei,pi,comic]);
 if(!comic)return <div className="empty">Comic tidak ditemukan.</div>;
 if(!episode)return <div><button className="btn" onClick={()=>navigate("comic-library")}>← Kembali</button><div className="card empty" style={{marginTop:14}}>Komik ini belum memiliki episode.</div></div>;
 function next(){if((episode.panels?.length||0)>0 && pi<episode.panels.length-1)setPi(v=>v+1);else if(ei<comic.episodes.length-1){setEi(v=>v+1);setPi(0)}}
 function prev(){if((episode.panels?.length||0)===0)return;if(pi>0)setPi(v=>v-1);else if(ei>0){const e=ei-1;setEi(e);setPi(Math.max(0,(comic.episodes[e].panels?.length||1)-1))}}
 function jumpToEpisode(i){setEi(i);setPi(0)}
 if(!panel){return <div><button className="btn" onClick={()=>navigate("comic-library")}>← Kembali</button><div className="card" style={{marginTop:14}}><div className="page-kicker">{comic.subject||"Matematika"}</div><h1 className="page-title">{comic.title}</h1><p className="page-desc">{comic.description||""}</p><h2>Episode</h2>{comic.episodes.map((item,index)=><button key={item.id||index} className={index===ei?"btn-primary":"btn"} style={{display:"block",width:"100%",margin:"8px 0",textAlign:"left"}} onClick={()=>jumpToEpisode(index)}>Episode {index+1} · {item.title} — {item.panels?.length||0} panel</button>)}</div></div>}
 async function answerQuiz(i){if(quizDiagnosis||!activeQuestion||!onAnswer)return;setQuizSelected(i);const duration=Math.floor((Date.now()-quizStartedAt.current)/1000);const d=await onAnswer(activeQuestion,i,"reader-quiz",duration);setQuizDiagnosis(d)}
 async function askAI(){setTutorBusy(true);try{await onTutorSend?.(`Jelaskan panel yang sedang saya baca dan hubungkan dengan konsep yang sedang dipelajari. Jika gambar panel tersedia, gunakan gambar sebagai konteks utama. Jika gambar belum tersedia, tetap jawab berdasarkan teks dan konteks panel.`,buildTutorContext())}finally{setTutorBusy(false)}}
 function buildTutorContext(){return {comicTitle:comic.title,episodeTitle:episode.title,panelTitle:panel.title,narration:panel.narration,dialogue:panel.dialogue,equation:panel.equation,imageUrl:panel.imageUrl||"",conceptId,conceptName,studentMastery:mastery,educationLevel:session?.educationLevel,grade:session?.grade,school:session?.school,currentLevel:studentModel?.currentLevel||1}}
 async function sendTutor(e){e.preventDefault();const msg=tutorInput.trim();if(!msg||tutorBusy)return;setTutorInput("");setTutorBusy(true);try{await onTutorSend?.(msg,buildTutorContext())}finally{setTutorBusy(false)}}
 const content=<div className={`reader-page ${focusMode?"reader-page-focus":""}`}>
  <div className="reader-toolbar"><button className="btn" onClick={()=>navigate("comic-library")}>← Koleksi</button><div className="reader-breadcrumb"><strong>{comic.title}</strong><span>Episode {ei+1} · {episode.title}</span></div><div className="reader-actions"><span className="reader-progress-pill">{overallProgress}% selesai</span><button className="btn" onClick={()=>setFocusMode(v=>!v)}>{focusMode?<Minimize2 size={16}/>:<Maximize2 size={16}/>} {focusMode?"Kembali ke normal":"Mode baca"}</button>{focusMode&&<button className="reader-icon-close" onClick={()=>setFocusMode(false)}><X size={18}/></button>}</div></div>
  <div className="reader-shell">
   <section className="reader-main-card"><div className="reader-heading"><div><div className="page-kicker">{comic.subject||"Matematika"} · Episode {ei+1}</div><h1>{episode.title}</h1><p className="reader-description">{episode.description||comic.description}</p></div><div className="reader-panel-meta"><span>Panel {pi+1}/{episode.panels.length}</span><b>{overallProgress}%</b></div></div><div className="reader-progress-track"><span style={{width:`${overallProgress}%`}}/></div>
    <div className="reader-art-wrap"><div className="reader-art-frame">{panel.imageUrl?<MediaImage src={panel.imageUrl} alt={panel.title||`Panel ${pi+1}`} style={{width:"100%",height:"auto",maxWidth:"100%",display:"block",objectFit:"contain",objectPosition:"center",borderRadius:14}} fallback={<div className="reader-art-fallback"><BookOpen size={40}/><span>Gambar panel belum tersedia.</span></div>} loadingFallback={<div className="reader-art-fallback"><BookOpen size={40}/><span>Memuat komik...</span></div>}/>:<div className="reader-art-fallback"><BookOpen size={40}/><span>Panel ini belum memiliki gambar.</span></div>}</div></div>
    <div className="reader-content-grid"><div className="reader-text-card"><div className="reader-section-title"><Info size={16}/> Cerita pada panel</div><h3>{panel.title||"Panel pembelajaran"}</h3>{panel.narration&&<p>{panel.narration}</p>}{panel.dialogue&&<div className="reader-dialogue">“{panel.dialogue}”</div>}{panel.equation&&<div className="equation-preview reader-equation" dangerouslySetInnerHTML={{__html:renderEquation(panel.equation)}}/>}</div><div className="reader-concept-card"><div className="reader-section-title"><Lightbulb size={16}/> Fokus belajar</div><Badge tone="blue">{conceptId||"Konsep"}</Badge><h3>{conceptName}</h3>{mastery!=null?<><div className="subtle">Mastery siswa: {Math.round(mastery*100)}%</div><div className="progress" style={{marginTop:7}}><span style={{width:`${mastery*100}%`}}/></div></>:<p className="subtle">Konsep ini menjadi fokus belajar dan latihan berikutnya.</p>}</div></div>
    <div className="reader-footer-nav"><button className="btn" disabled={ei===0&&pi===0} onClick={prev}>← Sebelumnya</button><div className="reader-counter"><span>{currentGlobalPanel}</span> / {totalPanels||1}</div><button className="btn-primary" disabled={ei===comic.episodes.length-1&&pi===episode.panels.length-1} onClick={next}>Selanjutnya →</button></div>
   </section>
   <aside className="reader-side-card"><div className="reader-side-tabs">{tabs.map(({id,label,icon:Icon})=><button key={id} className={infoTab===id?"active":""} onClick={()=>setInfoTab(id)}><Icon size={15}/><span>{label}</span></button>)}</div><div className="reader-side-body">
    {infoTab==="tutor"&&<div className="reader-info-panel ai reader-tutor-panel"><div className="reader-tutor-heading"><div><div className="reader-info-icon"><MessageCircle size={18}/></div><h3>AI Tutor · Panel ini</h3></div><button type="button" className="reader-chat-clear" onClick={onClearHistory} title="Hapus riwayat chat AI"><Trash2 size={14}/> Hapus riwayat</button></div><p className="reader-tutor-intro">Tanya langsung tentang gambar, cerita, atau konsep pada panel. AI Tutor membaca gambar panel yang sedang kamu lihat.</p><div className="reader-inline-chat" ref={tutorMessagesRef}>{tutorMessages.slice(-12).map((m,i)=><div key={i} className={`reader-chat-bubble ${m.role}`}><AIResponse text={m.text}/></div>)}{tutorBusy&&<div className="reader-chat-bubble assistant"><span className="reader-chat-typing">AI sedang berpikir…</span></div>}</div><form className="reader-chat-form" onSubmit={sendTutor}><input value={tutorInput} onChange={e=>setTutorInput(e.target.value)} placeholder="Tanya tentang panel ini…" disabled={tutorBusy}/><button className="btn-primary" disabled={tutorBusy||!tutorInput.trim()}>{tutorBusy?"…":"Kirim"}</button></form><button className="reader-chat-suggest" type="button" onClick={askAI} disabled={tutorBusy}>↗ Minta AI menjelaskan panel & konsep ini</button></div>}
    {infoTab==="tokoh"&&<div className="reader-info-panel"><div className="reader-info-icon"><Users size={18}/></div><h3>Tokoh pada panel</h3>{panel.characters?.length?<div className="list">{panel.characters.map((c,i)=><div className="list-item" key={i}><strong>{c}</strong><span>Tokoh cerita</span></div>)}</div>:<div className="reader-mini-note">Guru belum menambahkan tokoh pada panel ini.</div>}</div>}
    {infoTab==="kuis"&&<div className="reader-info-panel"><div className="reader-info-icon"><ClipboardList size={18}/></div><h3>Kuis cepat</h3>{activeQuestion?<><div className="subtle">{activeQuestion.conceptId} · Level {activeQuestion.level||activeQuestion.difficulty||1}</div><p><strong>{activeQuestion.question}</strong></p>{activeQuestion.equation&&<div className="equation-preview" dangerouslySetInnerHTML={{__html:renderEquation(activeQuestion.equation)}}/>}<div style={{display:"grid",gap:7}}>{activeQuestion.options.map((o,i)=><button className="option" key={i} disabled={!!quizDiagnosis} onClick={()=>answerQuiz(i)} style={quizSelected===i?{borderColor:i===activeQuestion.answer?"#10b981":"#ef4444"}:{}}>{String.fromCharCode(65+i)}. {o}</button>)}</div>{quizDiagnosis&&<div className={`feedback ${quizDiagnosis.correct?"good":"bad"}`}><strong>{quizDiagnosis.correct?"Benar":"Belum tepat"}</strong><AIResponse text={quizDiagnosis.explanation}/><button className="btn-primary" onClick={()=>navigate("practice")}>Lanjut latihan adaptif →</button></div>}</>:<div className="reader-mini-note">Belum ada soal yang dipetakan ke konsep panel ini.</div>}</div>}
    {infoTab==="materi"&&<div className="reader-info-panel"><div className="reader-info-icon"><BookOpen size={18}/></div><h3>Materi</h3><div className="reader-material-box"><strong>{conceptName}</strong><span>{comic.subject||"Matematika"} · Kelas {comic.grade||"-"}</span></div><p className="subtle">{episode.description||comic.description||"Belum ada ringkasan materi tambahan."}</p></div>}
    {infoTab==="progres"&&<div className="reader-info-panel"><div className="reader-info-icon"><TrendingUp size={18}/></div><h3>Progress membaca</h3><div className="reader-stat-row"><span>Panel dibaca</span><strong>{currentGlobalPanel}/{totalPanels||1}</strong></div><div className="reader-stat-row"><span>XP dari membaca</span><strong>{studentModel?.xp||0}</strong></div><div className="progress" style={{marginTop:8}}><span style={{width:`${overallProgress}%`}}/></div></div>}
   </div><div className="reader-episode-list"><div className="reader-section-title"><PanelRight size={16}/> Episode</div>{comic.episodes.map((item,index)=><button key={item.id} className={index===ei?"active":""} onClick={()=>jumpToEpisode(index)}><span>Episode {index+1}</span><strong>{item.title}</strong><small>{item.panels?.length||0} panel</small></button>)}</div></aside>
  </div>
  <div className="reader-tip-bar"><PlayCircle size={15}/><span>Tips: gunakan <strong>←</strong> dan <strong>→</strong> saat Mode Baca aktif.</span></div>
 </div>;
 return focusMode?<div className="reader-focus-overlay">{content}</div>:content;
}
