import React, { useEffect, useMemo, useState } from "react";
import { ClipboardCheck, Clock3, CheckCircle2 } from "lucide-react";
import katex from "katex";
import "katex/dist/katex.min.css";

const renderEquation=(value)=>{try{return katex.renderToString(value,{displayMode:true,throwOnError:false})}catch{return value}};

export default function ExamPage({ questions = [], session, onComplete }) {
  const eligible = useMemo(()=>questions.filter(q=>q.status !== "Draft" && (!q.educationLevel||q.educationLevel===session?.educationLevel) && (!q.grade||q.grade===session?.grade)).slice(0,20),[questions,session?.educationLevel,session?.grade]);
  const [started,setStarted]=useState(false); const [index,setIndex]=useState(0); const [answers,setAnswers]=useState({}); const [seconds,setSeconds]=useState(Math.max(300,eligible.length*90)); const [finished,setFinished]=useState(false); const [result,setResult]=useState(null);
  useEffect(()=>{if(!started||finished)return; const t=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(t);finish();return 0;}return s-1;}),1000);return()=>clearInterval(t);},[started,finished,index]);
  const q=eligible[index];
  const fmt=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
  async function finish(){ if(finished) return; const correct=eligible.filter((x,i)=>Number(answers[i])===Number(x.answer)).length; const score=eligible.length?Math.round((correct/eligible.length)*100):0; const res={score,correct,total:eligible.length,durationSeconds:(eligible.length*90)-seconds,answers}; setFinished(true);setResult(res);await onComplete?.(res,eligible,answers); }
  if(!eligible.length) return <div><div className="page-kicker">Assessment</div><h1 className="page-title">Ujian</h1><div className="card empty-state"><strong>Belum ada soal ujian yang tersedia.</strong><span>Guru perlu menerbitkan soal untuk jenjang dan kelas akunmu.</span></div></div>;
  if(finished) return <div><div className="page-kicker">Assessment Result</div><h1 className="page-title">Hasil Ujian</h1><div className="stats-row"><div className="ac-stat"><div className="stat-icon green"><CheckCircle2/></div><div><span>Nilai</span><strong>{result?.score||0}</strong></div></div><div className="ac-stat"><div className="stat-icon blue"><ClipboardCheck/></div><div><span>Benar</span><strong>{result?.correct||0}/{result?.total||0}</strong></div></div></div><div className="card"><h2>Ujian selesai</h2><p className="subtle">Hasil ujian sudah tersimpan pada riwayat belajarmu.</p><button className="primary-btn" onClick={()=>{setFinished(false);setStarted(false);setAnswers({});setIndex(0);setSeconds(Math.max(300,eligible.length*90));}}>Ulangi Ujian</button></div></div>;
  if(!started) return <div><div className="page-kicker">Assessment</div><h1 className="page-title">Ujian</h1><p className="page-desc">Ujian sumatif untuk mengukur penguasaan konsep setelah pembelajaran.</p><div className="exam-card"><div className="exam-icon"><ClipboardCheck/></div><h2>Ujian {session?.grade||""}</h2><p>Evaluasi {eligible.length} soal sesuai profil belajar.</p><div className="exam-meta"><span><ClipboardCheck size={15}/> {eligible.length} soal</span><span><Clock3 size={15}/> {Math.floor(seconds/60)} menit</span></div><button className="primary-btn" onClick={()=>setStarted(true)}>Mulai Ujian</button></div></div>;
  return <div><div className="page-kicker">Assessment</div><h1 className="page-title">Ujian Berlangsung</h1><div className="card" style={{marginBottom:14,display:"flex",justifyContent:"space-between",alignItems:"center"}}><strong>Soal {index+1} / {eligible.length}</strong><BadgeTime seconds={seconds}/></div><div className="card"><h2>{q.question}</h2>{q.equation&&<div className="equation-preview" dangerouslySetInnerHTML={{__html:renderEquation(q.equation)}}/>}<div style={{display:"grid",gap:10,marginTop:16}}>{q.options.map((o,i)=><button key={i} className={`option ${answers[index]===i?"selected":""}`} onClick={()=>setAnswers(a=>({...a,[index]:i}))}>{String.fromCharCode(65+i)}. {o}</button>)}</div><div className="actions" style={{marginTop:18}}><button className="btn" disabled={index===0} onClick={()=>setIndex(i=>i-1)}>← Sebelumnya</button>{index<eligible.length-1?<button className="btn-primary" onClick={()=>setIndex(i=>i+1)}>Berikutnya →</button>:<button className="btn-primary" onClick={finish}>Kumpulkan Ujian</button>}</div></div></div>;
}
function BadgeTime({seconds}){return <span className="badge badge-blue">⏱ {String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</span>}
