import React,{useMemo,useState} from "react";
import { Send, CalendarDays } from "lucide-react";
export default function ReflectionPage({session,reflections=[],onSave}){
 const today=new Date().toISOString().slice(0,10); const [date,setDate]=useState(today); const [text,setText]=useState(""); const [saved,setSaved]=useState(false);
 const mine=useMemo(()=>reflections.filter(r=>r.uid===session?.uid).slice().sort((a,b)=>String(b.date||b.createdAt||"").localeCompare(String(a.date||a.createdAt||""))),[reflections,session?.uid]);
 const existing=mine.find(r=>r.date===date); React.useEffect(()=>{setText(existing?.text||"");setSaved(false)},[date,existing?.id]);
 async function save(){if(!text.trim())return;await onSave({uid:session.uid,name:session.name,text:text.trim(),date,school:session.school||"",grade:session.grade||"",rombel:session.rombel||""});setSaved(true);}
 return <div><div className="page-kicker">Daily Journal</div><h1 className="page-title">Jurnal Harian</h1><p className="page-desc">Catat apa yang kamu pahami hari ini, bagian yang masih membingungkan, dan rencana belajarmu berikutnya.</p><div className="card reflection-card"><div className="field"><label className="label"><CalendarDays size={15}/> Tanggal jurnal</label><input type="date" value={date} max={today} onChange={e=>setDate(e.target.value)}/></div><h2>Apa yang kamu pelajari hari ini?</h2><textarea rows="8" value={text} onChange={e=>{setText(e.target.value);setSaved(false)}} placeholder="Contoh: Hari ini saya memahami sifat perkalian eksponen, tetapi masih bingung ketika basisnya berbeda..."/><button className="primary-btn" onClick={save}><Send size={16}/> {existing?"Perbarui Jurnal":"Simpan Jurnal Hari Ini"}</button>{saved&&<div className="success-note">Jurnal tersimpan untuk {new Date(`${date}T00:00:00`).toLocaleDateString("id-ID")}.</div>}</div><div className="card" style={{marginTop:16}}><h2>Riwayat Jurnal</h2>{mine.length?mine.map(r=><div className="list-item" key={r.id}><div><strong>{new Date(`${r.date||r.createdAt?.slice(0,10)}T00:00:00`).toLocaleDateString("id-ID")}</strong><div className="subtle">{r.text}</div></div></div>):<div className="empty-state"><strong>Belum ada jurnal.</strong><span>Setiap jurnal akan tersimpan berdasarkan tanggal.</span></div>}</div></div>;
}
