import React,{useMemo,useState} from "react";
import { concepts } from "../../data/demoData";
export default function TutorPage({comic,studentModel,messages,onSend,readerContext}){
 const [input,setInput]=useState("");const [busy,setBusy]=useState(false);
 const ei=readerContext?.episodeIndex||0,pi=readerContext?.panelIndex||0;const episode=comic?.episodes?.[ei];const panel=episode?.panels?.[pi];const conceptId=panel?.conceptIds?.[0]||comic?.concepts?.[0]||"E1";
 const context=useMemo(()=>({comicTitle:comic?.title||"Belum memilih E-Comic",episodeTitle:episode?.title||"",panelTitle:panel?.title||"",narration:panel?.narration||"",dialogue:panel?.dialogue||"",equation:panel?.equation||"",conceptId,conceptName:concepts[conceptId]?.name||conceptId,studentMastery:studentModel?.concepts?.[conceptId]?.mastery??null,misconceptions:(studentModel?.misconceptions||[]).filter(m=>m.conceptId===conceptId),educationLevel:studentModel?.educationLevel}),[comic,episode,panel,conceptId,studentModel]);
 async function send(e){e.preventDefault();if(!input.trim()||busy)return;const msg=input.trim();setInput("");setBusy(true);try{await onSend(msg,context)}finally{setBusy(false)}}
 return <div><div className="page-kicker">Contextual AI Tutor</div><h1 className="page-title">Tutor AI</h1><p className="page-desc">AI Tutor menerima konteks komik, panel, persamaan, konsep, dan student model agar jawabannya tetap relevan.</p><div className="split" style={{marginTop:18}}><div className="chat"><div className="chat-messages">{messages.map((m,i)=><div key={i} className={`bubble ${m.role}`}>{m.text}</div>)}</div><form className="chat-input" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Tanyakan konsep yang sedang kamu baca..."/><button className="btn-primary" disabled={busy}>{busy?"...":"Kirim"}</button></form></div><aside className="side-stack"><div className="card"><div className="label">Current Context</div><p><strong>Comic</strong><br/>{context.comicTitle}</p><p><strong>Episode</strong><br/>{context.episodeTitle||"-"}</p><p><strong>Panel</strong><br/>{context.panelTitle||"-"}</p><p><strong>Konsep</strong><br/>{context.conceptId} · {context.conceptName}</p><p><strong>Mastery</strong><br/>{context.studentMastery==null?"-":`${Math.round(context.studentMastery*100)}%`}</p>{context.equation&&<p><strong>Persamaan</strong><br/>{context.equation}</p>}</div><div className="card"><div className="label">Miskonsepsi</div>{context.misconceptions?.length?context.misconceptions.map((m,i)=><div key={i} className="list-item"><strong>{m.tag}</strong><span>{m.resolved?"terselesaikan":"aktif"}</span></div>):<div className="subtle">Belum ada miskonsepsi aktif pada konsep ini.</div>}</div></aside></div></div>;
}
