import React,{useMemo,useState} from "react";
import { concepts } from "../../data/demoData";
import { testAIConnection } from "../../services/tutorService";

export default function TutorPage({comic,studentModel,messages,onSend,readerContext,session}){
 const [input,setInput]=useState("");const [busy,setBusy]=useState(false);const [test,setTest]=useState(null);const [testing,setTesting]=useState(false);
 const ei=Number.isInteger(readerContext?.episodeIndex)?readerContext.episodeIndex:0,pi=Number.isInteger(readerContext?.panelIndex)?readerContext.panelIndex:0;
 const episode=comic?.episodes?.[ei];const panel=episode?.panels?.[pi];
 const conceptId=panel?.conceptIds?.[0]||comic?.concepts?.[0]||"E1";
 const context=useMemo(()=>({comicTitle:comic?.title||"Belum memilih E-Comic",episodeTitle:episode?.title||"",panelTitle:panel?.title||"",narration:panel?.narration||"",dialogue:panel?.dialogue||"",equation:panel?.equation||"",conceptId,conceptName:concepts[conceptId]?.name||conceptId,studentMastery:studentModel?.concepts?.[conceptId]?.mastery??0,misconceptions:(studentModel?.misconceptions||[]).filter(m=>m.conceptId===conceptId&&!m.resolved),educationLevel:session?.educationLevel,grade:session?.grade,school:session?.school,currentLevel:studentModel?.currentLevel||1}),[comic,episode,panel,conceptId,studentModel,session]);
 async function send(e){e.preventDefault();if(!input.trim()||busy)return;const msg=input.trim();setInput("");setBusy(true);try{await onSend(msg,context)}finally{setBusy(false)}}
 async function runTest(){setTesting(true);setTest(null);try{setTest(await testAIConnection())}catch(e){setTest({ok:false,error:e?.message||"Tidak dapat mengakses endpoint /api/ai-test"})}finally{setTesting(false)}}
 return <div><div className="page-kicker">Contextual AI Tutor</div><h1 className="page-title">Tutor AI</h1><p className="page-desc">Tutor membaca konteks E-Comic dan student model. Jika siswa meminta jawaban terus-menerus, tutor mengarahkannya kembali ke materi, memberi hint, dan mengajukan pertanyaan penuntun.</p>
 <div className="card" style={{marginTop:14,display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>AI Connection</strong><div className="subtle">Endpoint: /api/tutor · Model dikendalikan server</div></div><button className="btn" onClick={runTest} disabled={testing}>{testing?"Menguji AI…":"🧪 Tes koneksi AI"}</button>{test&&<div className={`success-note ${test.ok?"":"ai-feedback"}`} style={{marginTop:0,width:"100%"}}><strong>{test.ok?"AI TERHUBUNG":"AI BELUM TERHUBUNG"}</strong><div>{test.ok?`${test.response||"AI E-Comic OK"} · ${test.latencyMs||0} ms`: `${test.error||test.message||"Periksa Environment Variables Vercel."} · HTTP ${test.httpStatus||test.status||"-"}`}</div></div>}</div>
 <div className="split" style={{marginTop:18}}><div className="chat"><div className="chat-messages">{messages.map((m,i)=><div key={i} className={`bubble ${m.role}`}>{m.text}</div>)}</div><form className="chat-input" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Tanyakan konsep yang sedang kamu baca..."/><button className="btn-primary" disabled={busy}>{busy?"AI…":"Kirim"}</button></form></div><aside className="side-stack"><div className="card"><div className="label">Current Context</div><p><strong>Comic</strong><br/>{context.comicTitle}</p><p><strong>Episode</strong><br/>{context.episodeTitle||"-"}</p><p><strong>Panel</strong><br/>{context.panelTitle||"-"}</p><p><strong>Konsep</strong><br/>{context.conceptId} · {context.conceptName}</p><p><strong>Mastery</strong><br/>{Math.round(Number(context.studentMastery||0)*100)}%</p>{context.equation&&<p><strong>Persamaan</strong><br/>{context.equation}</p>}</div><div className="card"><div className="label">Miskonsepsi Aktif</div>{context.misconceptions?.length?context.misconceptions.map((m,i)=><div key={i} className="list-item"><strong>{m.tag}</strong><span>{m.resolved?"terselesaikan":"aktif"}</span></div>):<div className="subtle">Belum ada miskonsepsi aktif pada konsep ini.</div>}</div></aside></div></div>;
}
